export const catalogo = [
  { 
    id: 1, 
    marca: 'Zara', 
    nome: 'Camisa Larga com Bolsos', 
    valor: 70.00, 
    imagem: 'product-1.jpg', 
    feminino: false, 
  }, 
  { 
    id: 2, 
    marca: 'Zara', 
    nome: 'Casaco Reto com Lã', 
    valor: 85.00, 
    imagem: 'product-2.jpg', 
    feminino: true, 
  },     
  { 
    id: 3, 
    marca: 'Zara', 
    nome: 'Jaqueta com Efeito Camurça', 
    valor: 60.00, 
    imagem: 'product-3.jpg', 
    feminino: false, 
  },    
  { 
    id: 4, 
    marca: 'Zara', 
    nome: 'Sobretudo em Mescla de Lã', 
    valor: 160.00, 
    imagem: 'product-4.jpg', 
    feminino: false, 
  },     
  { 
    id: 5,
    marca: 'Zara', 
    nome: 'Camisa Larga Acolchoada de Veludo Cotelê', 
    valor: 110.00, 
    imagem: 'product-5.jpg', 
    feminino: false, 
  },     
  { 
    id: 6,
    marca: 'Zara', 
    nome: 'Casaco de Lã com Botões', 
    valor: 170.00, 
    imagem: 'product-6.jpg', 
    feminino: true, 
  }, 
  { 
    id: 7, 
    marca: 'Zara', 
    nome: 'Casaco com Botões', 
    valor: 75.00, 
    imagem: 'product-7.jpg', 
    feminino: true, 
  },     
  { 
    id: 8, 
    marca: 'Zara', 
    nome: 'Colete Comprido com Cinto', 
    valor: 88.00, 
    imagem: 'product-8.jpg', 
    feminino: true, 
  }, 
];
